{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mdns-controller.serviceAccountName" . }}
  namespace: {{ include "mdns-controller.namespace" . }}
{{- end }}
